baseURL = "https://dungg-z04.github.io/eam-workshop-report/"
relativeURLs = false
canonifyURLs = false
defaultContentLanguage = "en"

theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
  themeVariant = "eam"
  editURL = ""
  description = "Personal internship report and AWS deployment workshop for the EAM Workspace project."
  author = "Dung"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[languages]
[languages.en]
title = "EAM Workspace Internship Report"
weight = 1
locale = "en-US"
label = "English"

[[languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Repository"
identifier = "GitHub Repository"
url = "https://github.com/dungg-z04/eam-workshop-report"
weight = 20

[[languages.en.menu.shortcuts]]
name = "<i class='fas fa-project-diagram'></i> EAM Workspace"
identifier = "EAM Workspace"
url = "/2-Proposal/"
weight = 30

[languages.vi]
title = "Báo cáo thực tập EAM Workspace"
weight = 2
locale = "vi-VN"
label = "Tiếng Việt"

[[languages.vi.menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Repository"
identifier = "GitHub Repository"
url = "https://github.com/dungg-z04/eam-workshop-report"
weight = 20

[[languages.vi.menu.shortcuts]]
name = "<i class='fas fa-project-diagram'></i> EAM Workspace"
identifier = "EAM Workspace"
url = "/vi/2-Proposal/"
weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
